### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by JafferWilson** [effa/smartoo#1]
Dear sir, 
I try to run your code but after placing the wikipedia link it throwing server error. Kindly guide me what I need to do? Here is the screen shot of the error I encountered.  
![capture](https://cloud.githubusercontent.com/assets/13446197/25062997/3d7fe692-21f6-11e7-9c7a-5347f97efe87.PNG)

**Comment by effa** [comment]
Hello! It's quite a long time since I last touched this project, but I think that one needs to:

1. create a virtual environment for Python 2.7,
2. install requirements (`pip install -r requirements.txt`),
3. modify manage.py to point to `development.settings` instead of `production.settings` (that's my guess, sorry for this),
4. create test DB (`python manage.py syncdb; python manage.py migrate`),
5. collect static files (`python manage.py collectstatic`), and
6. start local development server (`python manage.py runserver`).

But as I said, it's quite an old project, so there might be some other problems along the way. I'm not sure it's worth the pain, depends what you want to do with it. It was only a prototype, a proof of concept. If you are considering creating a similar product, you can take a look at my bachelor thesis, where I described this prototype and related topics (https://is.muni.cz/auth/th/410350/fi_b/thesis.pdf).

**Comment by JafferWilson** [comment]
Thank you for your reply.
But as you can see I am getting the server error

**Comment by JafferWilson** [comment]
When I ran the command `python manage.py collectstatic`, I came across the following error.
```

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "c:\Python27\lib\site-packages\django\core\management\__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "c:\Python27\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\Python27\lib\site-packages\django\core\management\__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "c:\Python27\lib\site-packages\django\core\management\__init__.py", line 42, in load_command_class
    return module.Command()
  File "c:\Python27\lib\site-packages\django\contrib\staticfiles\management\commands\collectstatic.py", line 58, in __init__
    self.storage.path('')
  File "c:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 45, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.

```
If you can help me then it will be awesome, else need to search for some other:)

**Comment by effa** [comment]
I am not sure if the collectstatic command is actually needed for the development (as it seems that I didn't included corresponding setting to the development.settings). So maybe this part can be skipped and you can try to call `python manage.py runserver` anyway. If there is still the Server error, you can take a look on the output in both django console in terminal and javascript browser console to find some more details about the error.

**Comment by JafferWilson** [comment]
Thank you for your help.... :)
